language: objective-c
osx_image: xcode8.3
cache:
- bundler
- pip
before_install:
  - brew update
  - brew install yarn
  - brew outdated yarn || brew upgrade yarn
script:
- travis_retry .travis/run.sh
notifications:
  email: false
