language: objective-c
osx_image: xcode8.3
cache:
  - bundler
  - pip
before_install:
  - brew update
  - brew install yarn
  - brew outdated yarn || brew upgrade yarn
script:
  - .travis/run.sh
env:
  matrix:
  - LANE=ios
  - LANE=android
notifications:
  email: false
