language: generic

matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
      sudo: required
      env:
        - LANE='android'
      android:
        components:
          - build-tools-23.0.1
          - android-23
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
    - language: objective-c
      os: osx
      osx_image: xcode8.3
      env:
        - LANE='ios'

before_install:
  - .travis/before_install.sh
script:
  - .travis/run.sh

cache:
  bundler: true
  pip: true
  directories:
    - $HOME/.gradle
    - $HOME/.yarn-cache

# deploy:
#   - provider: npm
#     skip_cleanup: true
#     api_key: $NPM_API_KEY
#     on: tags

jobs:
  include:
    - stage: npm release
      node_js: "7"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on: tags

notifications:
  email: false
